// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuPDdjt2jEhaYqfXm-v_4IccBUkQa39lY',
    appId: '1:475293845300:web:5f92993f6e9f1da67c8761',
    messagingSenderId: '475293845300',
    projectId: 'newfirebase-b6a8d',
    authDomain: 'newfirebase-b6a8d.firebaseapp.com',
    storageBucket: 'newfirebase-b6a8d.appspot.com',
    measurementId: 'G-GT87994NKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-AwT-cIdoYPg0KumeQecR4bbYuN_KtE',
    appId: '1:475293845300:android:9341801f3fa4692b7c8761',
    messagingSenderId: '475293845300',
    projectId: 'newfirebase-b6a8d',
    storageBucket: 'newfirebase-b6a8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy7yWvkIDAWV6MQj8qqhekoOTF5joaLdI',
    appId: '1:475293845300:ios:b97c83ada6843c977c8761',
    messagingSenderId: '475293845300',
    projectId: 'newfirebase-b6a8d',
    storageBucket: 'newfirebase-b6a8d.appspot.com',
    iosBundleId: 'com.example.newfireabse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy7yWvkIDAWV6MQj8qqhekoOTF5joaLdI',
    appId: '1:475293845300:ios:b97c83ada6843c977c8761',
    messagingSenderId: '475293845300',
    projectId: 'newfirebase-b6a8d',
    storageBucket: 'newfirebase-b6a8d.appspot.com',
    iosBundleId: 'com.example.newfireabse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuPDdjt2jEhaYqfXm-v_4IccBUkQa39lY',
    appId: '1:475293845300:web:c2e11ccea8f120b37c8761',
    messagingSenderId: '475293845300',
    projectId: 'newfirebase-b6a8d',
    authDomain: 'newfirebase-b6a8d.firebaseapp.com',
    storageBucket: 'newfirebase-b6a8d.appspot.com',
    measurementId: 'G-5K6SR513HK',
  );
}
